=== josemj96/SW2-practica1/main/files/dtd/marca.dtd
<?xml version='1.0' encoding='UTF-8'?>

        <!ELEMENT marca (nombre|productos)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT nombre (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT productos (productos|nombre|tipo|descripcion|precio)*>
        <!ATTLIST productos
                fechaDePublicacion CDATA #IMPLIED
                >

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT tipo (#PCDATA)>
        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT descripcion (#PCDATA)>
        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT precio (#PCDATA)>

=== josemj96/SW2-practica1/main/files/xml/marca.xml
<?xml version="1.0"?>
<!DOCTYPE marca SYSTEM "../dtd/marca.dtd">
<marca>
    <nombre>Marca1</nombre>
    <productos>
        <productos fechaDePublicacion="25-03-2021">
            <nombre>Producto1</nombre>
            <tipo>Comida</tipo>
            <descripcion>Se come </descripcion>
            <precio>300.0</precio>
        </productos>
    </productos>

    <nombre>Marca2</nombre>
    <productos>
        <productos fechaDePublicacion="23-07-1996">
            <nombre>Reloj</nombre>
            <tipo>Complemento</tipo>
            <descripcion>Se pone </descripcion>
            <precio>33.23</precio>
        </productos>
    </productos>
    <nombre>Marca3</nombre>
    <productos>
        <productos fechaDePublicacion="26-10-1998">
            <nombre>Action Man</nombre>
            <tipo>Juguete</tipo>
            <descripcion>Se juega </descripcion>
            <precio>22.22</precio>
        </productos>
    </productos>
</marca>

=== josemj96/SW2-practica1/main/files/xml/marca2.xml
<?xml version="1.0"?>
<!DOCTYPE marca SYSTEM "../dtd/marca.dtd">
<marca>
    <nombre>Prueba</nombre>
    <productos>
        <productos fechaDePublicacion="1-01-2001">
            <nombre>Pruebita</nombre>
            <tipo>Probaci√≥n</tipo>
            <descripcion>Se prueba </descripcion>
            <precio>1000.0</precio>
        </productos>
    </productos>
</marca>
